---
name: Feature Request
about: 建议新功能
title: "[FEAT] "
labels: enhancement
---

## 功能描述
<!-- 想要的功能 -->

## 使用场景
<!-- 为什么需要这个功能？解决了什么问题？ -->

## 期望方案
<!-- 你希望怎么实现？ -->

## 备选方案
<!-- 可选，其他实现方式 -->

## 其他
<!-- 可选 -->
